### ISSUE TITLE
'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by iGetUploaded** [Tomato6966/discord-bot-maker#2]
I'm super new to this kind of stuff and I'm getting this error 

![image](https://user-images.githubusercontent.com/54633753/115809425-16669c00-a3ba-11eb-936f-04c0c51bb2a6.png)

**Comment by iGetUploaded** [comment]
I also node . and that still didn't work so I'm confused

**Comment by Tomato6966** [comment]
make sure that u are in the right directory
and this is just a public bot ...
